### ISSUE TITLE
"unauthorized_client" exception

### ISSUE THREAD

**Issue by attilaTM** [XeroAPI/Xero-NetStandard-custom-connections-starter#1]
After downloading the sample app and setting the proper ClientId and ClientSecret this line
var xeroToken = await client.RequestClientCredentialsTokenAsync();
throws the exception 'unauthorized_client'
What should I do to make this working?

**Comment by frowdester** [comment]
did you ever manage to get this working?

**Comment by attilaTM** [comment]
> did you ever manage to get this working?

No, at the end I forgot about the SDK and did the Xero integration with direct API calls

**Comment by brett-m** [comment]
So I did exactly the same and got the same error

1) Logged onto Xero Dev and got clientid and secret
2) hardcoded the clientid and secret into this sample app (not using environment variables)
3) ran it and get the error unauthorized_client.

Really don't want to do direct API calls though.

**Comment by RettBehrens** [comment]
Hi all. I just ran this custom connections starter app locally using a Client ID and Client Secret associated with my custom connection app and had no issues. I then swapped my Client ID and Client Secret for another set associated with my standard web auth app and encountered the same unauthorized client error. Please see [documentation](https://developer.xero.com/documentation/guides/oauth2/custom-connections) for further details. If you confirm you are using the appropriate custom connection app credentials and are still experiencing the issue please follow up here to reopen this issue. Thanks!

**Comment by brett-m** [comment]
Okay, I figured it out.  I think the Xero design is really silly especially for server-to-server interactions where there is no user interface or web interface.  Thus connecting through a UI first and authorising the API and choosing a tenant will not happen.  I had to modify your MVC app to create a UI and gain access.   I then stored the token and then loaded the app again and it worked.

Sorry, but this approval via UI is impractical for \server services that don't have a UI.  One should be able to connect with the secret credentials with no UI round-tripping.  My service will be deployed to azure and there is no UI.  I really don't want to have to deploy another UI admin site to connect and authenticate, unnecessary hosting costs.

**Comment by RettBehrens** [comment]
All Xero APIs require apps to operate on behalf of a user. Connecting your app to a Xero account requires a user to grant consent in a web browser. This can be challenging if you’re building a back-end integration that doesn’t have a user interface. 

For integrations like these, our CLI tool [XOAuth](https://github.com/XeroAPI/xoauth) allows you to establish an offline connection with a Xero user’s account directly from the command line. No web development required. See our guide on [machine-to-machine integrations](https://developer.xero.com/documentation/guides/how-to-guides/machine-2-machine/#connecting-your-app-to-a-xero-account) for more details.

Alternatively, Xero Custom Connections moves the required auth flow to an email to the user who needs to grant consent. A developer can specify the email address of the user who needs to grant consent and send the email via the Xero developer portal. Once consent is granted you can obtain a Client ID and Client Secret from the developer portal and run your integration without the need to implement the auth flow because it was handled separately via email from Xero. See our [Custom Connections](https://developer.xero.com/documentation/guides/oauth2/custom-connections) guide for details.

**Comment by brett-m** [comment]
Thanks for the link to XOAuth, I will give it a try.

Life would be so much easier if one could create the API Key and secret and in that same interface choose user, authenticate and give permissions as user and tenants.  It will eliminate the need for tools like XOAuth and life would be easy ... imagine that

**Comment by eden-chan** [comment]
Running into this issue as well. 
Deployed an app with the correct client_id and client_secret. Works locally, but not on production
<img width="338" alt="image" src="https://user-images.githubusercontent.com/60107091/227814130-d981bf1f-fbbf-4f05-b37e-d7ccc2222ba2.png">

```
oken response hooks.
[DEBUG]	2023-03-27T03:31:24.404Z	8fdf84a4-1bbc-402e-ab44-9401c5b18762	Invoking 0 token response hooks.
(unauthorized_client) 
[ERROR]	2023-03-27T03:31:24.404Z	8fdf84a4-1bbc-402e-ab44-9401c5b18762	Exception on /callback [GET]
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./api/index.py", line 333, in oauth_callback
    response = xero.authorized_response()
  File "/var/task/flask_oauthlib/contrib/client/application.py", line 267, in authorized_response
    token = oauth.fetch_token(
  File "/var/task/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/var/task/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/var/task/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/var/task/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/var/task/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) [WARNING]	2023-03-27T03:31:24.406Z	8fdf84a4-1bbc-402e-ab44-9401c5b18762	Exception raised while handling cache file '/var/task/cache/1cd0e0c4dd8dbd51dae9dcc5cc47bfef'
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./api/index.py", line 333, in oauth_callback
    response = xero.authorized_response()
  File "/var/task/flask_oauthlib/contrib/client/application.py", line 267, in authorized_response
    token = oauth.fetch_token(
  File "/var/task/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/var/task/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/var/task/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/var/task/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/var/task/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/cachelib/file.py", line 248, in set
    fd, tmp = tempfile.mkstemp(
  File "/var/lang/lib/python3.9/tempfile.py", line 336, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/var/lang/lib/python3.9/tempfile.py", line 255, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 30] Read-only file system: '/var/task/cache/tmplbox19j_.__wz_cache'
```

**Comment by RettBehrens** [comment]
@onlychans1 looks like you're working with python, could you take this to the python SDK repo?

Additionally, from your description that it works locally but not in production, my guess is your prod redirect uri isn't listed in the dev portal and your dev redirect uri is. Details on troubleshooting unauthorized_client https://developer.xero.com/documentation/guides/oauth2/troubleshooting

**Comment by Hillary-KG** [comment]
> Thanks for the link to XOAuth, I will give it a try.
> 
> Life would be so much easier if one could create the API Key and secret and in that same interface choose user, authenticate and give permissions as user and tenants. It will eliminate the need for tools like XOAuth and life would be easy ... imagine that

Hi @brett-m, did you manage to use XOAuth for the backend integration? I'm stuck here and I'd love to know how you went about it. Thanks!
